package relay

import (
	"strings"
	"testing"
)

func obfs4Config() Config {
	c := baseConfig()
	c.Mode = ModeBridge
	c.ORPort = 9443
	c.Bridge = Bridge{Transport: TransportObfs4, Plugin: Obfs4ProxyPath, Port: 8443, Distribution: "any"}
	return c
}

func webTunnelConfig() Config {
	c := baseConfig()
	c.Mode = ModeBridge
	c.Bridge = Bridge{
		Transport: TransportWebTunnel, Plugin: WebTunnelPath, Port: DefaultWebTunnelPort,
		Distribution: "https", URL: "https://bridge.example.org/Abc123secretPath",
	}
	return c
}

// The bridge blocks follow the Tor Project's guides line for line; both
// renders were accepted by tor 0.4.9.13 --verify-config (obfs4 and WebTunnel
// also ran with the real lyrebird/obfs4proxy and webtunnel-server binaries).
func TestRenderObfs4BridgeExact(t *testing.T) {
	c := obfs4Config()
	c.IPv6Address = "2001:db8::5"
	c.Sandbox = true // ignored: tor refuses transports with Sandbox 1
	got := string(c.Render("trs", testNow))
	want := `# Generated by trs on 2026-10-01 12:30:05 UTC.
# Tor relay configuration.
# Review Tor Project relay documentation before making manual changes.

Nickname MyRelay01
ContactInfo "email:ops[]example.org ciissversion:3"

# Bridge mode: unlisted entry point for users in censored networks.
BridgeRelay 1
ORPort 9443
ORPort [2001:db8::5]:9443
ServerTransportPlugin obfs4 exec /usr/bin/obfs4proxy
ServerTransportListenAddr obfs4 0.0.0.0:8443
# Local link between tor and the transport. Always auto.
ExtORPort auto
BridgeDistribution any

# Disable local SOCKS listener on this relay-only server.
SocksPort 0

# Keep potentially sensitive log details scrubbed.
SafeLogging 1
`
	if got != want {
		t.Fatalf("Render mismatch\n--- got ---\n%s--- want ---\n%s", got, want)
	}
}

func TestRenderWebTunnelBridgeExact(t *testing.T) {
	c := webTunnelConfig()
	c.FamilyIDs = []string{testFamilyID} // never rendered for a bridge
	got := string(c.Render("trs", testNow))
	want := `# Generated by trs on 2026-10-01 12:30:05 UTC.
# Tor relay configuration.
# Review Tor Project relay documentation before making manual changes.

Nickname MyRelay01
ContactInfo "email:ops[]example.org ciissversion:3"

# Bridge mode: unlisted entry point for users in censored networks.
BridgeRelay 1
# WebTunnel: the ORPort stays on localhost; the web server is the public side.
ORPort 127.0.0.1:auto
AssumeReachable 1
ServerTransportPlugin webtunnel exec /usr/bin/webtunnel-server
ServerTransportListenAddr webtunnel 127.0.0.1:15000
ServerTransportOptions webtunnel url=https://bridge.example.org/Abc123secretPath
# Local link between tor and the transport. Always auto.
ExtORPort auto
BridgeDistribution https

# Disable local SOCKS listener on this relay-only server.
SocksPort 0

# Keep potentially sensitive log details scrubbed.
SafeLogging 1
`
	if got != want {
		t.Fatalf("Render mismatch\n--- got ---\n%s--- want ---\n%s", got, want)
	}
}

func TestBridgeValidate(t *testing.T) {
	tests := []struct {
		name    string
		mutate  func(*Config)
		wantErr []string
	}{
		{"obfs4 ok", func(c *Config) {}, nil},
		{"webtunnel ok", func(c *Config) { *c = webTunnelConfig() }, nil},
		{"same port", func(c *Config) { c.Bridge.Port = c.ORPort }, []string{"must differ from the ORPort"}},
		{"relative plugin", func(c *Config) { c.Bridge.Plugin = "obfs4proxy" }, []string{"Plugin"}},
		{"bad port", func(c *Config) { c.Bridge.Port = 70000 }, []string{"bridge Port"}},
		{"bad distribution", func(c *Config) { c.Bridge.Distribution = "moat" }, []string{"BridgeDistribution"}},
		{"bad transport", func(c *Config) { c.Bridge.Transport = "snowflake" }, []string{"Transport"}},
		{"sandbox", func(c *Config) { c.Sandbox = true }, []string{"Sandbox"}},
		{"family", func(c *Config) { c.FamilyIDs = []string{testFamilyID} }, []string{"family"}},
		{"family pending", func(c *Config) { c.FamilyPending = true }, []string{"family"}},
		{"webtunnel http url", func(c *Config) {
			*c = webTunnelConfig()
			c.Bridge.URL = "http://bridge.example.org/Abc123secretPath"
		}, []string{"WebTunnel URL"}},
		{"webtunnel short path", func(c *Config) {
			*c = webTunnelConfig()
			c.Bridge.URL = "https://bridge.example.org/abc"
		}, []string{"WebTunnel URL"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			c := obfs4Config()
			tt.mutate(&c)
			err := c.Validate()
			if len(tt.wantErr) == 0 {
				if err != nil {
					t.Fatalf("Validate: %v", err)
				}
				return
			}
			if err == nil {
				t.Fatal("Validate accepted an invalid bridge")
			}
			for _, w := range tt.wantErr {
				if !strings.Contains(err.Error(), w) {
					t.Errorf("error %q does not mention %q", err, w)
				}
			}
		})
	}
}

func TestBridgeSettingsRoundTrip(t *testing.T) {
	for _, c := range []Config{obfs4Config(), webTunnelConfig()} {
		doc := ParseDocument(c.Render("trs", testNow))
		got, ok := doc.BridgeSettings()
		if !ok {
			t.Fatalf("%s: BridgeSettings not found", c.Bridge.Transport)
		}
		if got != c.Bridge {
			t.Errorf("BridgeSettings = %+v, want %+v", got, c.Bridge)
		}
	}
	if _, ok := ParseDocument(baseConfig().Render("trs", testNow)).BridgeSettings(); ok {
		t.Error("a guard relay reads back as a bridge")
	}
	doc := ParseDocument(obfs4Config().Render("trs", testNow))
	if got := doc.BridgePorts(); len(got) != 1 || got[0] != 8443 {
		t.Errorf("BridgePorts = %v", got)
	}
	if got := doc.FirstORPort(); got != 9443 {
		t.Errorf("FirstORPort = %d", got)
	}
	if got := ParseDocument(webTunnelConfig().Render("trs", testNow)).FirstORPort(); got != 0 {
		t.Errorf("WebTunnel FirstORPort = %d, want 0 (127.0.0.1:auto)", got)
	}
}

func TestWebTunnelURL(t *testing.T) {
	tests := []struct {
		in, domain, path string
		ok               bool
	}{
		{"https://bridge.example.org/Abc123secretPath", "bridge.example.org", "Abc123secretPath", true},
		{"https://bridge.example.org/abc", "", "", false},
		{"https://bridge.example.org/", "", "", false},
		{"https://bridge.example.org/a/b/cdefghij", "", "", false},
		{"http://bridge.example.org/Abc123secretPath", "", "", false},
		{"https://203.0.113.5/Abc123secretPath", "", "", false},
		{"https://localhost/Abc123secretPath", "", "", false},
	}
	for _, tt := range tests {
		d, p, ok := SplitWebTunnelURL(tt.in)
		if d != tt.domain || p != tt.path || ok != tt.ok {
			t.Errorf("SplitWebTunnelURL(%q) = %q, %q, %v", tt.in, d, p, ok)
		}
	}
	if got := WebTunnelURL("bridge.example.org", "/Abc123secretPath"); got != "https://bridge.example.org/Abc123secretPath" {
		t.Errorf("WebTunnelURL = %q", got)
	}
	for s, want := range map[string]bool{
		"example.org": true, "a.b.example.co.uk": true, "example": false, "10.0.0.1": false,
		"exa mple.org": false, "-bad.example.org": false, "example.123": false,
	} {
		if ValidDomain(s) != want {
			t.Errorf("ValidDomain(%q) = %v, want %v", s, !want, want)
		}
	}
}
