package relay

import (
	"strings"
	"testing"
	"time"
)

const (
	testFamilyID  = "AbCdEfGhIjKlMnOpQrStUvWxYz0123456789+/abcde"
	testFamilyID2 = "ZZCdEfGhIjKlMnOpQrStUvWxYz0123456789+/abcde"
)

var testNow = time.Date(2026, 10, 1, 14, 30, 5, 0, time.FixedZone("CEST", 2*3600))

func baseConfig() Config {
	return Config{
		Nickname:    "MyRelay01",
		ContactInfo: `email:ops[]example.org ciissversion:3`,
		ORPort:      9001,
		Mode:        ModeGuard,
	}
}

func TestRenderGuardExact(t *testing.T) {
	c := baseConfig()
	c.Sandbox = true
	got := string(c.Render("trs", testNow))
	want := `# Generated by trs on 2026-10-01 12:30:05 UTC.
# Tor relay configuration.
# Review Tor Project relay documentation before making manual changes.

Nickname MyRelay01
ContactInfo "email:ops[]example.org ciissversion:3"

ORPort 9001

# Disable local SOCKS listener on this relay-only server.
SocksPort 0

# Guard / middle relay mode.
ExitRelay 0

# Keep potentially sensitive log details scrubbed.
SafeLogging 1
Sandbox 1
`
	if got != want {
		t.Fatalf("Render mismatch\n--- got ---\n%s--- want ---\n%s", got, want)
	}
}

func TestRenderFullExact(t *testing.T) {
	c := baseConfig()
	c.Mode = ModeExit
	c.ExitPolicy = PolicyReduced
	c.IPv6Exit = true
	c.IPv6Address = "2001:db8::5"
	c.ORPort = 443
	c.FamilyIDs = []string{testFamilyID}
	c.MetricsPort = "127.0.0.1:9035"
	plan, err := Steady(9313, 10, RuleSum)
	if err != nil {
		t.Fatal(err)
	}
	c.Bandwidth = plan.Bandwidth
	if err := c.Validate(); err != nil {
		t.Fatalf("Validate: %v", err)
	}
	got := string(c.Render("trs", testNow))
	want := `# Generated by trs on 2026-10-01 12:30:05 UTC.
# Tor relay configuration.
# Review Tor Project relay documentation before making manual changes.

Nickname MyRelay01
ContactInfo "email:ops[]example.org ciissversion:3"

# Managed relay family (Tor 0.4.9 FamilyId). Every relay in the family shares the key.
FamilyId ` + testFamilyID + `

ORPort 443
ORPort [2001:db8::5]:443

# Disable local SOCKS listener on this relay-only server.
SocksPort 0

# Exit relay mode.
ExitRelay 1
ReducedExitPolicy 1
IPv6Exit 1

# Keep potentially sensitive log details scrubbed.
SafeLogging 1

# Local-only Prometheus metrics. Never expose this port publicly.
MetricsPort 127.0.0.1:9035
MetricsPortPolicy accept 127.0.0.1

# Relay-specific bandwidth limits. Tor applies these per second.
RelayBandwidthRate 1640 KBytes
RelayBandwidthBurst 8200 KBytes

# Monthly accounting safety cap. Tor hibernates if this is exhausted.
AccountingStart month 1 00:00
AccountingRule sum
AccountingMax 8381 GBytes
`
	if got != want {
		t.Fatalf("Render mismatch\n--- got ---\n%s--- want ---\n%s", got, want)
	}
}

func TestRenderVariants(t *testing.T) {
	tests := []struct {
		name    string
		mutate  func(*Config)
		want    []string
		notWant []string
	}{
		{
			name:    "guard has no exit options",
			mutate:  func(c *Config) { c.IPv6Exit = true },
			want:    []string{"ExitRelay 0\n"},
			notWant: []string{"ExitRelay 1", "IPv6Exit", "ReducedExitPolicy", "Sandbox", "MetricsPort", "RelayBandwidth", "Accounting", "FamilyId"},
		},
		{
			name:    "exit default policy",
			mutate:  func(c *Config) { c.Mode, c.ExitPolicy = ModeExit, PolicyDefault },
			want:    []string{"# Exit relay mode.\nExitRelay 1\n\n"},
			notWant: []string{"ReducedExitPolicy", "IPv6Exit"},
		},
		{
			name:   "family pending placeholder",
			mutate: func(c *Config) { c.FamilyPending = true },
			want:   []string{"ContactInfo \"email:ops[]example.org ciissversion:3\"\n\n# FamilyId <generated with tor --keygen-family during apply>\n\nORPort 9001\n"},
		},
		{
			name:    "family ids win over pending",
			mutate:  func(c *Config) { c.FamilyPending = true; c.FamilyIDs = []string{testFamilyID, testFamilyID2} },
			want:    []string{"FamilyId " + testFamilyID + "\nFamilyId " + testFamilyID2 + "\n"},
			notWant: []string{"<generated"},
		},
		{
			name:   "ipv6 metrics port",
			mutate: func(c *Config) { c.MetricsPort = "[::1]:9035" },
			want:   []string{"MetricsPort [::1]:9035\nMetricsPortPolicy accept [::1]\n"},
		},
		{
			name:   "other loopback metrics host",
			mutate: func(c *Config) { c.MetricsPort = "127.0.0.2:9035" },
			want:   []string{"MetricsPortPolicy accept 127.0.0.2\n"},
		},
		{
			name: "manual bandwidth",
			mutate: func(c *Config) {
				c.Bandwidth = Bandwidth{Mode: BandwidthManual, RateMbit: 20, BurstMbit: 40}
			},
			want:    []string{"RelayBandwidthRate 20 MBits\nRelayBandwidthBurst 40 MBits\n"},
			notWant: []string{"Accounting"},
		},
		{
			name: "accounting only, max rule omitted",
			mutate: func(c *Config) {
				c.Bandwidth = Bandwidth{Mode: BandwidthAccounting, AccountingMaxGBytes: 500, AccountingRule: RuleMax}
			},
			want:    []string{"# Monthly accounting safety cap. Tor hibernates if this is exhausted.\nAccountingStart month 1 00:00\nAccountingMax 500 GBytes\n"},
			notWant: []string{"AccountingRule", "RelayBandwidth"},
		},
		{
			name: "accounting out rule",
			mutate: func(c *Config) {
				c.Bandwidth = Bandwidth{Mode: BandwidthAccounting, AccountingMaxGBytes: 500, AccountingRule: RuleOut}
			},
			want: []string{"AccountingRule out\nAccountingMax 500 GBytes\n"},
		},
		{
			name: "none ignores stray fields",
			mutate: func(c *Config) {
				c.Bandwidth = Bandwidth{Mode: BandwidthNone, RateKBytes: 5000, AccountingMaxGBytes: 9}
			},
			notWant: []string{"RelayBandwidth", "Accounting"},
		},
		{
			name:   "contact info is quoted and escaped",
			mutate: func(c *Config) { c.ContactInfo = `a "b" \c` },
			want:   []string{`ContactInfo "a \"b\" \\c"` + "\n"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			c := baseConfig()
			tt.mutate(&c)
			got := string(c.Render("trs", testNow))
			for _, w := range tt.want {
				if !strings.Contains(got, w) {
					t.Errorf("missing %q in:\n%s", w, got)
				}
			}
			for _, nw := range tt.notWant {
				if strings.Contains(got, nw) {
					t.Errorf("unexpected %q in:\n%s", nw, got)
				}
			}
		})
	}
}

func TestRenderRoundTripsThroughDocument(t *testing.T) {
	c := baseConfig()
	c.IPv6Address = "2001:db8::1"
	c.FamilyIDs = []string{testFamilyID}
	c.MetricsPort = "127.0.0.1:9035"
	c.Bandwidth = Bandwidth{Mode: BandwidthManual, RateMbit: 20, BurstMbit: 40, AccountingMaxGBytes: 100, AccountingRule: RuleSum}
	data := c.Render("trs", testNow)
	d := ParseDocument(data)
	if nick, _ := d.Get("nickname"); nick != c.Nickname {
		t.Errorf("Nickname = %q", nick)
	}
	if ci, _ := d.Get("ContactInfo"); Unquote(ci) != c.ContactInfo {
		t.Errorf("ContactInfo = %q", ci)
	}
	if got := d.FamilyIDs(); len(got) != 1 || got[0] != testFamilyID {
		t.Errorf("FamilyIDs = %v", got)
	}
	if got := d.FirstORPort(); got != 9001 {
		t.Errorf("FirstORPort = %d", got)
	}
	// Re-applying the same managed settings must not change the file.
	d.SetFamilyIDs(c.FamilyIDs)
	d.SetMetricsPort(c.MetricsPort)
	if got := string(d.Bytes()); got != string(data) {
		t.Errorf("re-applying family/metrics changed the file:\n%s", got)
	}
	d.SetBandwidth(c.Bandwidth)
	d.SetBandwidth(c.Bandwidth)
	got := string(d.Bytes())
	if n := strings.Count(got, "AccountingMax"); n != 1 {
		t.Errorf("AccountingMax appears %d times", n)
	}
	if strings.Contains(got, rateComment) || strings.Contains(got, accountingComment) {
		t.Errorf("stale render comments remain:\n%s", got)
	}
	if !strings.HasSuffix(got, "MetricsPortPolicy accept 127.0.0.1\n\n"+bandwidthComment+
		"\nRelayBandwidthRate 20 MBits\nRelayBandwidthBurst 40 MBits\nAccountingStart month 1 00:00\nAccountingRule sum\nAccountingMax 100 GBytes\n") {
		t.Errorf("unexpected bandwidth block:\n%s", got)
	}
}

func TestValidate(t *testing.T) {
	tests := []struct {
		name    string
		mutate  func(*Config)
		wantErr []string // substrings; nil = valid
	}{
		{name: "valid guard", mutate: func(*Config) {}},
		{name: "valid exit", mutate: func(c *Config) {
			c.Mode, c.ExitPolicy, c.IPv6Address, c.IPv6Exit = ModeExit, PolicyReduced, "2001:db8::1", true
			c.FamilyIDs = []string{testFamilyID}
			c.MetricsPort = "[::1]:9035"
			c.Bandwidth = Bandwidth{Mode: BandwidthSteady, RateKBytes: 2000, BurstKBytes: 10000, AccountingMaxGBytes: 1000, AccountingRule: RuleSum}
		}},
		{name: "bad nickname", mutate: func(c *Config) { c.Nickname = "has space" }, wantErr: []string{"Nickname"}},
		{name: "long nickname", mutate: func(c *Config) { c.Nickname = strings.Repeat("a", 20) }, wantErr: []string{"Nickname"}},
		{name: "contact hash", mutate: func(c *Config) { c.ContactInfo = "a#b" }, wantErr: []string{"ContactInfo"}},
		{name: "port zero", mutate: func(c *Config) { c.ORPort = 0 }, wantErr: []string{"ORPort"}},
		{name: "bad ipv6", mutate: func(c *Config) { c.IPv6Address = "[2001:db8::1]" }, wantErr: []string{"IPv6Address"}},
		{name: "bad mode", mutate: func(c *Config) { c.Mode = "bridge" }, wantErr: []string{"Mode"}},
		{name: "exit needs policy", mutate: func(c *Config) { c.Mode = ModeExit }, wantErr: []string{"ExitPolicy"}},
		{name: "bad family id", mutate: func(c *Config) { c.FamilyIDs = []string{"short"} }, wantErr: []string{"FamilyIDs"}},
		{name: "public metrics", mutate: func(c *Config) { c.MetricsPort = "0.0.0.0:9035" }, wantErr: []string{"MetricsPort"}},
		{name: "metrics without port", mutate: func(c *Config) { c.MetricsPort = "127.0.0.1" }, wantErr: []string{"MetricsPort"}},
		{name: "steady burst below rate", mutate: func(c *Config) {
			c.Bandwidth = Bandwidth{Mode: BandwidthSteady, RateKBytes: 2000, BurstKBytes: 10}
		}, wantErr: []string{"BurstKBytes"}},
		{name: "manual zero rate", mutate: func(c *Config) {
			c.Bandwidth = Bandwidth{Mode: BandwidthManual}
		}, wantErr: []string{"RateMbit"}},
		{name: "accounting zero", mutate: func(c *Config) {
			c.Bandwidth = Bandwidth{Mode: BandwidthAccounting}
		}, wantErr: []string{"AccountingMaxGBytes"}},
		{name: "bad rule", mutate: func(c *Config) {
			c.Bandwidth = Bandwidth{Mode: BandwidthAccounting, AccountingMaxGBytes: 5, AccountingRule: "in"}
		}, wantErr: []string{"AccountingRule"}},
		{name: "bad bandwidth mode", mutate: func(c *Config) { c.Bandwidth.Mode = "turbo" }, wantErr: []string{"bandwidth Mode"}},
		{name: "several errors reported together", mutate: func(c *Config) {
			c.Nickname, c.ORPort = "", 70000
		}, wantErr: []string{"Nickname", "ORPort"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			c := baseConfig()
			tt.mutate(&c)
			err := c.Validate()
			if tt.wantErr == nil {
				if err != nil {
					t.Fatalf("unexpected error: %v", err)
				}
				return
			}
			if err == nil {
				t.Fatalf("expected error mentioning %v", tt.wantErr)
			}
			for _, w := range tt.wantErr {
				if !strings.Contains(err.Error(), w) {
					t.Errorf("error %q does not mention %q", err, w)
				}
			}
		})
	}
}
