package status

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"reflect"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/ljkx/tor-relay-setup/internal/family"
	"github.com/ljkx/tor-relay-setup/internal/host"
	"github.com/ljkx/tor-relay-setup/internal/onionoo"
)

var (
	famA = strings.Repeat("A", 42) + "a"
	famB = strings.Repeat("B", 42) + "b"
)

const (
	fingerprint = "abcdef0123456789abcdef0123456789abcdef01"

	goodTorrc = `# Generated by tor-relay-setup
Nickname GoodRelay
ContactInfo "email:ops[]example.org \"quoted\" ciissversion:2"

# Managed relay family (Tor 0.4.9 FamilyId). Every relay in the family shares the key.
FamilyId ` + "FAMILY_A" + `

ORPort 9001
ORPort [2001:db8::1]:9001
SocksPort 0
ExitRelay 0
SafeLogging 1
Sandbox 1

MetricsPort 127.0.0.1:9035
MetricsPortPolicy accept 127.0.0.1

RelayBandwidthRate 1640 KBytes
RelayBandwidthBurst 8200 KBytes
AccountingStart month 1 00:00
AccountingRule sum
AccountingMax 8381 GBytes
`

	procTCPHeader = "  sl  local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode\n"
	// 0x2329 = 9001, 0A = LISTEN.
	procTCPListen  = procTCPHeader + "   0: 00000000:2329 00000000:0000 0A 00000000:00000000 00:00000000 00000000   109        0 1234 1 0000000000000000 100 0 0 10 0\n"
	procTCP6Listen = procTCPHeader + "   0: 00000000000000000000000000000000:2329 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000   109        0 1235 1 0000000000000000 100 0 0 10 0\n"
	// A connection to port 9001 that is established (01), not listening.
	procTCPNoListen = procTCPHeader + "   0: 0100007F:2329 0100007F:D431 01 00000000:00000000 00:00000000 00000000   109        0 1236 1 0000000000000000 20 4 30 10 -1\n"

	selfTestV4 = "2026-03-04T05:10:00+0000 relay Tor[812]: Self-testing indicates your ORPort 203.0.113.5:9001 is reachable from the outside. Excellent.\n"
	selfTestV6 = "2026-03-04T05:11:00+0000 relay Tor[812]: Self-testing indicates your ORPort [2001:db8::1]:9001 is reachable from the outside. Excellent. Publishing server descriptor.\n"
	selfFailed = "2026-03-04T06:00:00+0000 relay Tor[812]: Your server has not managed to confirm reachability for its ORPort(s) at 203.0.113.5:9001. Relays do not publish descriptors until their ORPort and DirPort are reachable.\n"
	bootstrap  = "2026-03-04T05:00:00+0000 relay Tor[812]: Bootstrapped 100% (done): Done\n"
)

func secretKey() []byte {
	key := make([]byte, 96)
	copy(key, family.KeyHeader)
	return key
}

// fixture is a relay host described by its parts; fake() assembles it.
type fixture struct {
	files      map[string]string
	torVersion string // "" means tor is not installed
	active     bool
	journal    string
	journalErr bool
}

func goodFixture() *fixture {
	return &fixture{
		files: map[string]string{
			"/etc/tor/torrc":                           strings.Replace(goodTorrc, "FAMILY_A", famA, 1),
			"/var/lib/tor/fingerprint":                 "GoodRelay " + fingerprint + "\n",
			"/var/lib/tor/keys/fam.secret_family_key":  string(secretKey()),
			"/var/lib/tor/keys/fam.public_family_id":   famA + "\n",
			"/var/lib/tor/keys/ed25519_master_id_key":  "not a family key",
			"/var/lib/tor/keys/junk.secret_family_key": "too short",
			"/proc/net/tcp":                            procTCPListen,
			"/proc/net/tcp6":                           procTCP6Listen,
		},
		torVersion: "Tor version 0.4.9.3.\nTor is running on Linux with Libevent 2.1.12-stable.\n",
		active:     true,
		journal:    bootstrap + selfTestV4 + selfTestV6,
	}
}

func (fx *fixture) fake() *host.Fake {
	f := host.NewFake()
	for p, data := range fx.files {
		f.Files[p] = []byte(data)
	}
	f.Handler = func(c host.Command) (host.Result, error) {
		fail := func(code int) (host.Result, error) {
			return host.Result{ExitCode: code}, &host.ExitError{Command: c.String(), ExitCode: code}
		}
		switch c.Name {
		case "tor":
			if fx.torVersion == "" {
				return host.Result{}, errors.New("tor: executable file not found in $PATH")
			}
			return host.Result{Output: fx.torVersion}, nil
		case "systemctl":
			if len(c.Args) > 0 && c.Args[0] == "is-active" && fx.active {
				return host.Result{}, nil
			}
			return fail(3)
		case "journalctl":
			if fx.journalErr {
				return fail(1)
			}
			return host.Result{Output: fx.journal}, nil
		}
		return fail(127)
	}
	return f
}

func collect(t *testing.T, f *host.Fake, opt Options) Report {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	return Collect(ctx, f, opt)
}

func hasWarning(r Report, sub string) bool {
	return slices.ContainsFunc(r.Warnings, func(w string) bool { return strings.Contains(w, sub) })
}

func TestCollectHealthyRelay(t *testing.T) {
	t.Parallel()
	r := collect(t, goodFixture().fake(), Options{})

	if !r.Healthy() || len(r.Warnings) != 0 {
		t.Fatalf("Healthy() = false, warnings: %q", r.Warnings)
	}
	if r.CollectedAt.IsZero() {
		t.Error("CollectedAt not set")
	}
	if !r.Tor.Installed || r.Tor.Version != "0.4.9.3" || !r.Tor.Supported {
		t.Errorf("Tor = %+v", r.Tor)
	}
	if r.Service.Unit != "tor@default" || !r.Service.Active {
		t.Errorf("Service = %+v", r.Service)
	}
	rl := r.Relay
	if !rl.Configured || rl.Nickname != "GoodRelay" || rl.ORPort != 9001 || !rl.IPv6 || rl.Exit || !rl.Sandbox {
		t.Errorf("Relay = %+v", rl)
	}
	if rl.Contact != `email:ops[]example.org "quoted" ciissversion:2` {
		t.Errorf("Contact = %q, want it unquoted", rl.Contact)
	}
	if rl.Fingerprint != strings.ToUpper(fingerprint) {
		t.Errorf("Fingerprint = %q, want upper-case %s", rl.Fingerprint, fingerprint)
	}
	if rl.MetricsPort != "127.0.0.1:9035" {
		t.Errorf("MetricsPort = %q", rl.MetricsPort)
	}
	// The exact wording is presentation; the values must be there.
	if !strings.HasPrefix(rl.Bandwidth, "1640 KBytes") || !strings.Contains(rl.Bandwidth, "burst 8200 KBytes") {
		t.Errorf("Bandwidth = %q, want rate 1640 KBytes and burst 8200 KBytes", rl.Bandwidth)
	}
	if !strings.HasPrefix(rl.Accounting, "8381 GBytes") || !strings.HasSuffix(rl.Accounting, "sum") {
		t.Errorf("Accounting = %q, want 8381 GBytes with rule sum", rl.Accounting)
	}
	if !r.Listener.IPv4 || !r.Listener.IPv6 {
		t.Errorf("Listener = %+v, want IPv4 and IPv6", r.Listener)
	}
	if rc := r.Reachability; !rc.IPv4 || !rc.IPv6 || rc.Failed || !rc.Seen {
		t.Errorf("Reachability = %+v", rc)
	}
	fam := r.Family
	if !reflect.DeepEqual(fam.IDs, []string{famA}) || fam.KeyDirectory != "/var/lib/tor/keys" || len(fam.MissingKeys) != 0 || fam.LegacyCount != 0 {
		t.Errorf("Family = %+v", fam)
	}
	wantKeys := []family.Key{{Name: "fam", Path: "/var/lib/tor/keys/fam.secret_family_key", ID: famA}}
	if !reflect.DeepEqual(fam.Keys, wantKeys) {
		t.Errorf("Keys = %+v, want %+v (invalid key files skipped)", fam.Keys, wantKeys)
	}
	if len(r.RecentLog) != 3 || !strings.Contains(r.RecentLog[2], "[2001:db8::1]:9001") {
		t.Errorf("RecentLog = %q", r.RecentLog)
	}
}

func TestCollectWarnings(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name    string
		mutate  func(fx *fixture)
		opt     Options
		want    []string // expected warning substrings; nil means healthy
		notWant []string
		check   func(t *testing.T, r Report)
	}{
		{
			name: "FamilyId without its key",
			mutate: func(fx *fixture) {
				delete(fx.files, "/var/lib/tor/keys/fam.secret_family_key")
				delete(fx.files, "/var/lib/tor/keys/fam.public_family_id")
			},
			want: []string{"no family key installed for FamilyId " + famA},
			check: func(t *testing.T, r Report) {
				if !reflect.DeepEqual(r.Family.MissingKeys, []string{famA}) || len(r.Family.Keys) != 0 {
					t.Errorf("Family = %+v", r.Family)
				}
			},
		},
		{
			name:   "key for another family",
			mutate: func(fx *fixture) { fx.files["/var/lib/tor/keys/fam.public_family_id"] = famB + "\n" },
			want:   []string{"no family key installed for FamilyId " + famA},
		},
		{
			name: "one of two FamilyIds lacks a key",
			mutate: func(fx *fixture) {
				fx.files["/etc/tor/torrc"] = strings.Replace(fx.files["/etc/tor/torrc"], "FamilyId "+famA, "FamilyId "+famA+"\nFamilyId "+famB, 1)
			},
			want:    []string{"FamilyId " + famB},
			notWant: []string{"FamilyId " + famA},
		},
		{
			name: "legacy MyFamily only",
			mutate: func(fx *fixture) {
				fx.files["/etc/tor/torrc"] = strings.Replace(fx.files["/etc/tor/torrc"], "FamilyId "+famA,
					"MyFamily $"+strings.Repeat("1", 40)+",$"+strings.Repeat("2", 40), 1)
			},
			want: []string{"only a legacy MyFamily list is configured"},
			check: func(t *testing.T, r Report) {
				if r.Family.LegacyCount != 2 || len(r.Family.IDs) != 0 {
					t.Errorf("Family = %+v", r.Family)
				}
			},
		},
		{
			name: "MyFamily next to FamilyId is fine",
			mutate: func(fx *fixture) {
				fx.files["/etc/tor/torrc"] += "MyFamily " + strings.Repeat("3", 40) + "\n"
			},
			check: func(t *testing.T, r Report) {
				if r.Family.LegacyCount != 1 {
					t.Errorf("LegacyCount = %d", r.Family.LegacyCount)
				}
			},
		},
		{
			name:   "old tor",
			mutate: func(fx *fixture) { fx.torVersion = "Tor version 0.4.8.16.\n" },
			want:   []string{"tor 0.4.8.16 is older than 0.4.9 and is rejected by the network"},
			check: func(t *testing.T, r Report) {
				if !r.Tor.Installed || r.Tor.Supported || r.Tor.Version != "0.4.8.16" {
					t.Errorf("Tor = %+v", r.Tor)
				}
			},
		},
		{
			name:   "tor release candidate of the minimum is supported",
			mutate: func(fx *fixture) { fx.torVersion = "Tor version 0.4.9.1-alpha (git-abc).\n" },
		},
		{
			name:   "tor not installed",
			mutate: func(fx *fixture) { fx.torVersion = "" },
			want:   []string{"tor is not installed"},
		},
		{
			name:   "unparseable tor version",
			mutate: func(fx *fixture) { fx.torVersion = "something else\n" },
			check: func(t *testing.T, r Report) {
				if !r.Tor.Installed || r.Tor.Version != "" || r.Tor.Supported {
					t.Errorf("Tor = %+v", r.Tor)
				}
			},
		},
		{
			name: "service inactive",
			mutate: func(fx *fixture) {
				fx.active = false
				fx.files["/proc/net/tcp"], fx.files["/proc/net/tcp6"] = procTCPHeader, procTCPHeader
			},
			want:    []string{"tor@default is not running"},
			notWant: []string{"listening"}, // a stopped service cannot listen; one warning is enough
		},
		{
			name: "active but not listening",
			mutate: func(fx *fixture) {
				fx.files["/proc/net/tcp"] = procTCPNoListen
				delete(fx.files, "/proc/net/tcp6")
			},
			want: []string{"nothing is listening on the ORPort"},
			check: func(t *testing.T, r Report) {
				if r.Listener.IPv4 || r.Listener.IPv6 {
					t.Errorf("Listener = %+v", r.Listener)
				}
			},
		},
		{
			name:   "IPv4 listener only",
			mutate: func(fx *fixture) { delete(fx.files, "/proc/net/tcp6") },
			check: func(t *testing.T, r Report) {
				if !r.Listener.IPv4 || r.Listener.IPv6 {
					t.Errorf("Listener = %+v", r.Listener)
				}
			},
		},
		{
			name:   "reachability failed",
			mutate: func(fx *fixture) { fx.journal = bootstrap + selfFailed },
			want:   []string{"Tor could not confirm the ORPort is reachable from outside"},
			check: func(t *testing.T, r Report) {
				if rc := r.Reachability; rc.IPv4 || !rc.Failed || !rc.Seen {
					t.Errorf("Reachability = %+v", rc)
				}
			},
		},
		{
			name:   "failure notice after an IPv4 success is not a warning",
			mutate: func(fx *fixture) { fx.journal = selfTestV4 + selfFailed },
			check: func(t *testing.T, r Report) {
				if rc := r.Reachability; !rc.IPv4 || !rc.Failed || rc.IPv6 {
					t.Errorf("Reachability = %+v", rc)
				}
			},
		},
		{
			name:   "no self-test in the window",
			mutate: func(fx *fixture) { fx.journal = bootstrap },
			check: func(t *testing.T, r Report) {
				if r.Reachability.Seen {
					t.Errorf("Reachability = %+v, want nothing seen", r.Reachability)
				}
			},
		},
		{
			name:   "journal unavailable",
			mutate: func(fx *fixture) { fx.journalErr = true },
			check: func(t *testing.T, r Report) {
				if r.Reachability.Seen || r.RecentLog != nil {
					t.Errorf("Reachability = %+v, RecentLog = %q", r.Reachability, r.RecentLog)
				}
			},
		},
		{
			name: "no torrc means nothing to check",
			mutate: func(fx *fixture) {
				delete(fx.files, "/etc/tor/torrc")
				fx.active = false
			},
			check: func(t *testing.T, r Report) {
				if r.Relay.Configured || r.Relay.Fingerprint != "" || r.Family.KeyDirectory != "" {
					t.Errorf("Relay = %+v, Family = %+v", r.Relay, r.Family)
				}
			},
		},
		{
			name: "torrc without ORPort is not configured",
			mutate: func(fx *fixture) {
				fx.files["/etc/tor/torrc"] = "SocksPort 9050\n"
				fx.active = false
			},
			check: func(t *testing.T, r Report) {
				if r.Relay.Configured || r.Relay.ORPort != 0 {
					t.Errorf("Relay = %+v", r.Relay)
				}
			},
		},
		{
			name: "custom data and family key directories",
			mutate: func(fx *fixture) {
				fx.files["/etc/tor/torrc"] += "DataDirectory /srv/tor/\nFamilyKeyDirectory /etc/tor/family\n"
				for _, p := range []string{"/var/lib/tor/fingerprint", "/var/lib/tor/keys/fam.secret_family_key", "/var/lib/tor/keys/fam.public_family_id"} {
					delete(fx.files, p)
				}
				fx.files["/srv/tor/fingerprint"] = "GoodRelay 0123456789012345678901234567890123456789\n"
				fx.files["/etc/tor/family/fam.secret_family_key"] = string(secretKey())
				fx.files["/etc/tor/family/fam.public_family_id"] = famA
			},
			check: func(t *testing.T, r Report) {
				if r.Relay.Fingerprint != "0123456789012345678901234567890123456789" || r.Family.KeyDirectory != "/etc/tor/family" || len(r.Family.Keys) != 1 {
					t.Errorf("Fingerprint = %q, Family = %+v", r.Relay.Fingerprint, r.Family)
				}
			},
		},
		{
			name:   "exit relay without limits",
			mutate: func(fx *fixture) { fx.files["/etc/tor/torrc"] = "Nickname X\nORPort 443\nExitRelay 1\n" },
			check: func(t *testing.T, r Report) {
				rl := r.Relay
				if !rl.Exit || rl.Sandbox || rl.IPv6 || rl.ORPort != 443 || rl.Bandwidth != "" || rl.Accounting != "" || rl.MetricsPort != "" {
					t.Errorf("Relay = %+v", rl)
				}
				if r.Listener.IPv4 {
					t.Error("fixture listens on 9001, not 443")
				}
			},
			want: []string{"nothing is listening"},
		},
		{
			name: "accounting without a rule defaults to max",
			mutate: func(fx *fixture) {
				fx.files["/etc/tor/torrc"] = strings.Replace(fx.files["/etc/tor/torrc"], "AccountingRule sum\n", "", 1)
			},
			check: func(t *testing.T, r Report) {
				if !strings.HasPrefix(r.Relay.Accounting, "8381 GBytes") || !strings.HasSuffix(r.Relay.Accounting, "max") {
					t.Errorf("Accounting = %q", r.Relay.Accounting)
				}
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			fx := goodFixture()
			tt.mutate(fx)
			r := collect(t, fx.fake(), tt.opt)
			for _, w := range tt.want {
				if !hasWarning(r, w) {
					t.Errorf("warnings %q lack %q", r.Warnings, w)
				}
			}
			for _, w := range tt.notWant {
				if hasWarning(r, w) {
					t.Errorf("warnings %q unexpectedly contain %q", r.Warnings, w)
				}
			}
			if len(tt.want) == 0 && !r.Healthy() {
				t.Errorf("Healthy() = false, warnings %q", r.Warnings)
			}
			if len(tt.want) > 0 && r.Healthy() {
				t.Error("Healthy() = true despite warnings")
			}
			if tt.check != nil {
				tt.check(t, r)
			}
		})
	}
}

func TestCollectRecentLog(t *testing.T) {
	t.Parallel()
	var b strings.Builder
	b.WriteString("-- Boot 0123456789abcdef --\n")
	for i := 1; i <= 12; i++ {
		fmt.Fprintf(&b, "2026-03-04T05:%02d:00+0000 relay Tor[812]: line %d\n", i, i)
		if i == 10 {
			b.WriteString("\n   \n-- Boot fedcba9876543210 --\n")
		}
	}
	fx := goodFixture()
	fx.journal = b.String()
	r := collect(t, fx.fake(), Options{})
	if len(r.RecentLog) != 8 {
		t.Fatalf("RecentLog has %d lines, want 8: %q", len(r.RecentLog), r.RecentLog)
	}
	for i, line := range r.RecentLog {
		if want := fmt.Sprintf("line %d", i+5); !strings.HasSuffix(line, want) {
			t.Errorf("RecentLog[%d] = %q, want it to end with %q", i, line, want)
		}
	}
}

func TestCollectOptions(t *testing.T) {
	t.Parallel()
	fx := goodFixture()
	fx.files["/etc/relay/torrc"] = fx.files["/etc/tor/torrc"]
	delete(fx.files, "/etc/tor/torrc")
	f := fx.fake()
	r := collect(t, f, Options{TorrcPath: "/etc/relay/torrc", Unit: "tor@relay", Window: 90 * time.Minute})
	if !r.Relay.Configured || r.Service.Unit != "tor@relay" {
		t.Errorf("Relay.Configured = %v, Service = %+v", r.Relay.Configured, r.Service)
	}
	if !f.Ran("systemctl", "is-active", "--quiet", "tor@relay") {
		t.Errorf("no is-active check for the custom unit: %q", f.CommandLines())
	}
	if !f.Ran("journalctl", "-u", "tor@relay", "--since", "-90min") {
		t.Errorf("journal not read for the custom unit and window: %q", f.CommandLines())
	}
	if !f.Ran("tor", "--version") {
		t.Errorf("tor --version not run: %q", f.CommandLines())
	}
	for _, c := range f.Commands {
		if c.Mutates {
			t.Errorf("status ran a mutating command: %s", c)
		}
	}

	// Defaults: 24 hour window and tor@default.
	f = goodFixture().fake()
	collect(t, f, Options{})
	if !f.Ran("journalctl", "-u", "tor@default", "--no-pager", "--since", "-1440min") {
		t.Errorf("default journal window not used: %q", f.CommandLines())
	}
}

func TestReportJSON(t *testing.T) {
	t.Parallel()
	r := collect(t, goodFixture().fake(), Options{})
	data, err := json.Marshal(r)
	if err != nil {
		t.Fatal(err)
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		t.Fatal(err)
	}
	for _, k := range []string{"collected_at", "tor", "service", "relay", "listener", "reachability", "family"} {
		if _, ok := m[k]; !ok {
			t.Errorf("JSON lacks %q: %s", k, data)
		}
	}
	for _, k := range []string{"RecentLog", "warnings", "directory", "directory_error"} {
		if _, ok := m[k]; ok {
			t.Errorf("JSON unexpectedly has %q: %s", k, data)
		}
	}
	relay, _ := m["relay"].(map[string]any)
	if relay["or_port"] != float64(9001) || relay["nickname"] != "GoodRelay" {
		t.Errorf("relay JSON = %v", relay)
	}
}

func TestDirectoryWithoutFingerprint(t *testing.T) {
	t.Parallel()
	r, err := Directory(context.Background(), onionoo.Client{}, "")
	if r != nil || err != nil {
		t.Errorf("Directory(\"\") = %v, %v; want nil, nil without a network call", r, err)
	}
}
