# shellcheck shell=bash
# Sourced (hidden) at the start of docs/demo/*.tape recordings, and by the
# end-to-end tests. It builds a throw-away fixture server -- a running relay,
# or a fresh server with `source docs/demo/demo-env.sh fresh` -- and
# stubs the system commands, so every run looks the same and nothing on the
# machine is touched. The binary reads the fixture through
# TOR_RELAY_SETUP_ROOT, which it only honours together with --dry-run.

demo_root=$(mktemp -d)
demo_bin="${demo_root}/.bin"
mkdir -p "${demo_root}/etc/tor" "${demo_root}/var/lib/tor/keys" "${demo_root}/proc/net" \
  "${demo_root}/proc/sys/kernel" "${demo_root}/run/systemd/system" "$demo_bin"

cat > "${demo_root}/etc/os-release" << 'EOF'
PRETTY_NAME="Debian GNU/Linux 13 (trixie)"
NAME="Debian GNU/Linux"
VERSION_ID="13"
VERSION_CODENAME=trixie
ID=debian
EOF
printf 'MemTotal:        2014208 kB\n' > "${demo_root}/proc/meminfo"
printf 'relay-01\n' > "${demo_root}/proc/sys/kernel/hostname"
# One LISTEN socket on port 9001 (0x2329).
cat > "${demo_root}/proc/net/tcp" << 'EOF'
  sl  local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode
   0: 00000000:2329 00000000:0000 0A 00000000:00000000 00:00000000 00000000   109        0 31337 1 0000000000000000 100 0 0 10 0
EOF
: > "${demo_root}/proc/net/tcp6"

family_id="flIHuuYy2vCWg+FgNibpOOHpRQ7rALbVUlS0WMmmuI8"
if [[ "${1:-relay}" != "fresh" ]]; then
  cat > "${demo_root}/etc/tor/torrc" << EOF
# Generated by tor-relay-setup v3.0.0.
Nickname ExampleRelay
ContactInfo "email:ops[]example.org url:https://example.org proof:uri-familyid-ed25519 ciissversion:3"

# Managed relay family (Tor 0.4.9 FamilyId). Every relay in the family shares the key.
FamilyId ${family_id}

ORPort 9001
SocksPort 0
ExitRelay 0
SafeLogging 1
Sandbox 1

# Local-only Prometheus metrics. Never expose this port publicly.
MetricsPort 127.0.0.1:9035
MetricsPortPolicy accept 127.0.0.1

RelayBandwidthRate 1640 KBytes
RelayBandwidthBurst 8200 KBytes
AccountingStart month 1 00:00
AccountingRule sum
AccountingMax 8381 GBytes
EOF
  printf 'ExampleRelay 7D4698A1B2C3D4E5F60718293A4B5C6D7E8F9012\n' > "${demo_root}/var/lib/tor/fingerprint"
  {
    printf '== ed25519v1-secret: fmly-id ==\0'
    head -c 64 /dev/zero
  } > "${demo_root}/var/lib/tor/keys/relay-family.secret_family_key"
  printf '%s\n' "$family_id" > "${demo_root}/var/lib/tor/keys/relay-family.public_family_id"

fi

cat > "${demo_bin}/systemctl" << 'EOF'
#!/bin/sh
exit 0
EOF
cat > "${demo_bin}/tor" << 'EOF'
#!/bin/sh
case "$*" in
  *--version*) echo "Tor version 0.4.9.13." ;;
esac
exit 0
EOF
cat > "${demo_bin}/journalctl" << 'EOF'
#!/bin/sh
emit() {
  cat << 'LOG'
2026-10-01T09:12:01+0000 relay-01 Tor[812]: Tor 0.4.9.13 running on Linux with Libevent 2.1.12-stable, OpenSSL 3.5.1.
2026-10-01T09:12:02+0000 relay-01 Tor[812]: Read configuration file "/etc/tor/torrc".
2026-10-01T09:12:03+0000 relay-01 Tor[812]: Bootstrapped 100% (done): Done
2026-10-01T09:12:04+0000 relay-01 Tor[812]: Now checking whether IPv4 ORPort 203.0.113.5:9001 is reachable... (this may take up to 20 minutes -- look for log messages indicating success)
2026-10-01T09:12:31+0000 relay-01 Tor[812]: Self-testing indicates your ORPort 203.0.113.5:9001 is reachable from the outside. Excellent. Publishing server descriptor.
2026-10-01T09:13:02+0000 relay-01 Tor[812]: Performing bandwidth self-test...done.
LOG
}
case " $* " in
  *" -f "*)
    emit
    i=0
    while :; do
      sleep 2
      i=$((i + 1))
      echo "2026-10-01T10:0$((i % 10)):00+0000 relay-01 Tor[812]: Heartbeat: Tor's uptime is 1 day 0:0$i hours, with $((1400 + i * 7)) circuits open. I've sent 412.$i GB and received 409.$i GB."
    done
    ;;
  *) emit ;;
esac
EOF
printf '#!/bin/sh\necho "Status: inactive"\n' > "${demo_bin}/ufw"
chmod +x "${demo_bin}"/*

export TOR_RELAY_SETUP_ROOT="$demo_root"

# Live traffic and Tor Metrics for the console demo (`make demo` builds it).
if [[ "${1:-relay}" != "fresh" ]] && command -v fakerelay > /dev/null 2>&1; then
  fakerelay > /dev/null 2>&1 &
  demo_fakerelay=$!
  trap 'kill "$demo_fakerelay" 2> /dev/null' EXIT
  export TOR_RELAY_SETUP_ONIONOO_URL="http://127.0.0.1:9036"
fi
export PATH="${demo_bin}:${PATH}"
export TERM=xterm-256color
unset NO_COLOR
PS1='\[\e[38;5;141m\]operator@relay-01\[\e[0m\]:\[\e[38;5;81m\]~\[\e[0m\]# '
clear
