// Package family manages Tor 0.4.9 relay family keys (the FamilyId
// mechanism that replaces MyFamily). A family key is a 96-byte ed25519
// secret generated by `tor --keygen-family NAME`, stored in Tor's key
// directory as NAME.secret_family_key next to NAME.public_family_id, the
// base64 FamilyId that goes into torrc.
package family

import (
	"bytes"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"filippo.io/edwards25519"

	"github.com/ljkx/tor-relay-setup/internal/host"
)

// KeyHeader starts every secret family key file.
const KeyHeader = "== ed25519v1-secret: fmly-id =="

// keySize is the exact size of a secret family key file.
const keySize = 96

const (
	secretSuffix = ".secret_family_key"
	publicSuffix = ".public_family_id"
)

var (
	idPattern   = regexp.MustCompile(`^[A-Za-z0-9+/]{43}$`)
	namePattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$`)
)

// Key is an installed family key.
type Key struct {
	Name string // file name without the .secret_family_key suffix
	Path string // path of the secret key file
	ID   string // FamilyId from the sibling .public_family_id, else derived from the key
}

// ValidKey reports whether data looks like a secret family key: exactly 96
// bytes starting with KeyHeader.
func ValidKey(data []byte) bool {
	return len(data) == keySize && bytes.HasPrefix(data, []byte(KeyHeader))
}

// IDFromSecret derives the FamilyId of a secret family key: the unpadded
// base64 of its ed25519 public key. The file holds a 32-byte header and
// tor's 64-byte expanded secret key, whose first half is the clamped
// scalar. "" when data is not a valid key. tor needs only the secret key,
// so relays set up by hand often have no NAME.public_family_id.
func IDFromSecret(data []byte) string {
	if !ValidKey(data) {
		return ""
	}
	s, err := edwards25519.NewScalar().SetBytesWithClamping(data[32:64])
	if err != nil {
		return ""
	}
	return base64.RawStdEncoding.EncodeToString(new(edwards25519.Point).ScalarBaseMult(s).Bytes())
}

// ValidID reports whether id is a FamilyId: 43 unpadded base64 characters.
func ValidID(id string) bool { return idPattern.MatchString(id) }

// ValidName reports whether name is usable as a key name: 1–64 characters
// of letters, digits, '.', '_' and '-', starting with a letter or digit.
func ValidName(name string) bool { return namePattern.MatchString(name) }

// KeyDirectory returns the directory Tor reads family keys from: the
// torrc FamilyKeyDirectory, else KeyDirectory, else DataDirectory/keys
// (DataDirectory defaulting to /var/lib/tor). Trailing slashes are trimmed.
func KeyDirectory(familyKeyDir, keyDir, dataDir string) string {
	dir := familyKeyDir
	if dir == "" {
		dir = keyDir
	}
	if dir == "" {
		if dataDir == "" {
			dataDir = "/var/lib/tor"
		}
		dir = filepath.Join(dataDir, "keys")
	}
	if trimmed := strings.TrimRight(dir, "/"); trimmed != "" {
		return trimmed
	}
	return "/"
}

// Installed lists the valid secret family keys in dir, sorted by path.
// Files that are not valid keys are skipped. A missing or unreadable
// directory yields no keys.
func Installed(h host.Host, dir string) ([]Key, error) {
	paths, err := h.Glob(filepath.Join(dir, "*"+secretSuffix))
	if err != nil {
		return nil, err
	}
	var keys []Key
	for _, p := range paths {
		data, err := h.ReadFile(p)
		if err != nil || !ValidKey(data) {
			continue
		}
		k := Key{Name: strings.TrimSuffix(filepath.Base(p), secretSuffix), Path: p}
		if raw, err := h.ReadFile(strings.TrimSuffix(p, secretSuffix) + publicSuffix); err == nil {
			if id := strings.TrimSpace(string(raw)); ValidID(id) {
				k.ID = id
			}
		}
		if k.ID == "" {
			// tor needs only the secret key, so keys copied by hand
			// usually come without NAME.public_family_id.
			k.ID = IDFromSecret(data)
		}
		keys = append(keys, k)
	}
	return keys, nil
}

// HasKeyFor reports whether keys include one for FamilyId id; "*" matches
// any key.
func HasKeyFor(keys []Key, id string) bool {
	for _, k := range keys {
		if id == "*" || (id != "" && k.ID == id) {
			return true
		}
	}
	return false
}

// Generate creates a family key named name with `tor --keygen-family`,
// running tor inside workDir (a real temporary directory owned by the
// caller) with empty torrc files so the live configuration and its Sandbox
// setting stay out of the way. On a dry-run host tor is not run and
// Generate returns (nil, "", nil).
func Generate(ctx context.Context, h host.Host, workDir, name string) (secret []byte, id string, err error) {
	if !ValidName(name) {
		return nil, "", fmt.Errorf("invalid family key name %q: use 1-64 letters, digits, '.', '_' or '-'", name)
	}
	empty := filepath.Join(workDir, "empty.torrc")
	if err := os.WriteFile(empty, nil, 0o600); err != nil {
		return nil, "", fmt.Errorf("prepare family key generation: %w", err)
	}
	cmd := host.Command{
		Name:    "tor",
		Args:    []string{"--defaults-torrc", empty, "-f", empty, "--keygen-family", name},
		Dir:     workDir,
		Mutates: true,
	}
	if _, err := h.Run(ctx, cmd); err != nil {
		return nil, "", fmt.Errorf("generate family key %s: %w", name, err)
	}
	if h.DryRun() {
		return nil, "", nil
	}

	secretPath := filepath.Join(workDir, name+secretSuffix)
	secret, err = os.ReadFile(secretPath)
	if err != nil {
		return nil, "", fmt.Errorf("tor --keygen-family did not produce %s: %w", name+secretSuffix, err)
	}
	if !ValidKey(secret) {
		return nil, "", fmt.Errorf("tor --keygen-family produced an invalid %s", name+secretSuffix)
	}
	raw, err := os.ReadFile(filepath.Join(workDir, name+publicSuffix))
	if err != nil {
		return nil, "", fmt.Errorf("tor --keygen-family did not produce %s: %w", name+publicSuffix, err)
	}
	id = strings.TrimSpace(string(raw))
	if !ValidID(id) {
		return nil, "", fmt.Errorf("tor --keygen-family produced an invalid FamilyId in %s", name+publicSuffix)
	}
	return secret, id, nil
}

// Install writes a secret family key and its public FamilyId into dir as
// NAME.secret_family_key and NAME.public_family_id (mode 0600, owned by
// owner), creating dir with mode 0700. Installing the identical key again
// succeeds; a different existing key is never overwritten. On a dry-run
// host secret and id may be empty (a key that was not generated): the
// writes are still issued so the host reports them.
func Install(h host.Host, dir, name string, secret []byte, id, owner string) error {
	if !ValidName(name) {
		return fmt.Errorf("invalid family key name %q", name)
	}
	dry := h.DryRun()
	if !dry || secret != nil {
		if !ValidKey(secret) {
			return errors.New("refusing to install an invalid family key")
		}
		if !ValidID(id) {
			return fmt.Errorf("invalid FamilyId %q", id)
		}
	}

	target := filepath.Join(dir, name+secretSuffix)
	existing, err := h.ReadFile(target)
	switch {
	case err == nil && bytes.Equal(existing, secret):
		// Already installed; make sure the public ID sits next to it.
		return writeID(h, dir, name, id, owner)
	case err == nil:
		return fmt.Errorf("a different family key already exists at %s; choose another key name (existing keys are never overwritten)", target)
	case errors.Is(err, fs.ErrNotExist):
	case dry && errors.Is(err, fs.ErrPermission):
		// A dry run as a normal user cannot look into Tor's key directory.
	default:
		return fmt.Errorf("check existing family key: %w", err)
	}

	if err := h.MkdirAll(dir, 0o700, owner); err != nil {
		return fmt.Errorf("create family key directory: %w", err)
	}
	if _, err := h.WriteFile(target, secret, host.FileOptions{Mode: 0o600, Owner: owner}); err != nil {
		return fmt.Errorf("install family key: %w", err)
	}
	return writeID(h, dir, name, id, owner)
}

func writeID(h host.Host, dir, name, id, owner string) error {
	path := filepath.Join(dir, name+publicSuffix)
	if _, err := h.WriteFile(path, []byte(id+"\n"), host.FileOptions{Mode: 0o600, Owner: owner}); err != nil {
		return fmt.Errorf("install family id: %w", err)
	}
	return nil
}

// ShareInstructions explains how to add another relay to the family: copy
// each key and its public ID to root@target:/root/ with scp, import it there,
// then delete the copies. target defaults to NEW-RELAY.
func ShareInstructions(keys []Key, target string) string {
	if target == "" {
		target = "NEW-RELAY"
	}
	var b strings.Builder
	b.WriteString("Add another relay to this family\n\n")
	if len(keys) == 0 {
		b.WriteString("No family key is installed on this relay yet. Generate one first.\n")
		return b.String()
	}
	b.WriteString("1. Copy the secret key and its public ID to the new relay, for example:\n\n")
	for _, k := range keys {
		id := strings.TrimSuffix(k.Path, secretSuffix) + publicSuffix
		fmt.Fprintf(&b, "   scp %s %s %s\n", host.Quote(k.Path), host.Quote(id), host.Quote("root@"+target+":/root/"))
		if k.ID != "" {
			fmt.Fprintf(&b, "   (FamilyId %s)\n", k.ID)
		}
	}
	b.WriteString("\n2. On the new relay, run this installer and choose \"Import an existing family key\"\n")
	b.WriteString("   (guided setup) or \"Relay family\" > \"Import family key\" (operator console).\n\n")
	b.WriteString("3. Delete the copies from /root on the new relay afterwards.\n\n")
	b.WriteString("The secret key proves family membership. Treat it like a relay identity key:\n")
	b.WriteString("transfer it only over SSH and keep it out of backups you share.\n")
	return b.String()
}
